name: Windows Build

on: 
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        default: 'latest-windows'

jobs:
  build:
    runs-on: windows-latest

    #uses: leotomas/chroma-fighters/.github/workflows/setup.yml@main
    #with:
    #  host: 'windows'

    steps:
    - uses: actions/checkout@v1
    - name: setup haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.4
    
    - name: setup libs
      run: |
        haxelib install hxcpp --always --quiet
        haxelib install hscript --always --quiet
        haxelib install json2object --always --quiet
        haxelib install ase --always --quiet
        haxelib install lime --always --quiet
        haxelib install openfl --always --quiet
        haxelib install flixel --always --quiet
        haxelib install flixel-addons --always --quiet
        echo "y" \| haxelib run openfl setup
    - name: build
      run: haxelib run openfl build windows -debug
    - name: archive
      uses: thedoctor0/zip-release@master
      with:
        type: zip
        filename: './windows.zip'
    - name: release on github
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        #allowUpdates: true
        automatic_release_tag: "${{ inputs.tag }}"
        prerelease: true
        title: "Windows Development Build"
        files: |
          ./windows.zip